### PR TITLE
Port to typescript

### PR DESCRIPTION
**Pull request by fd**

### CODE REVIEW

**Comment by Mike-E-angelo** [comment]
Dang even TypeScript support is off the table...

😞

**Comment by boredland** [comment]
why has this not been merged?

**Comment by kevgo** [comment]
It's irritating to see useful contributions like this auto-closed by a stale-bot without any comments from the maintainers.

**Comment by mirusky** [comment]
No mainterners in this repo apparently

**Comment by Laurianti** [comment]
Could you merge this please?

Or this:
#20

closes #10
closes #19
closes #22

**Pull request closed without merging**
